################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenge HTTP
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: kin3303@gmail.com
      storage: ./letsencrypt/acme.json
      tlsChallenge: true
  myresolver2:
    acme:
      email: kin3303@gmail.com
      storage: ./letsencrypt/acme2.json
      tlsChallenge: true
